before_install:
 - chmod +x gradlew

language: java
jdk:
  - oraclejdk8
  
cache:
  directories:
    - $HOME/.gradle/caches/2.11
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper